# Deployment manifest file for a Node.js backend application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-be
  labels:
    app: crud-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-be
  template:
    metadata:
      labels:
        app: crud-be
    spec:
      containers:
        - name: crud-be
          image: ahadalichowdhury/crud-be-devops:latest
          ports:
            - containerPort: 5000 # Ensure this matches the port your Node.js app is listening on